splits:
    -
        prefix: "src/Xezilaires"
        target: "https://${GH_TOKEN}@github.com/sigwinhq/xezilaires.git"
    -
        prefix: "src/Bridge/PhpSpreadsheet"
        target: "https://${GH_TOKEN}@github.com/sigwinhq/xezilaires-phpspreadsheet.git"
    -
        prefix: "src/Bridge/Spout"
        target: "https://${GH_TOKEN}@github.com/sigwinhq/xezilaires-spout.git"
    -
        prefix: "src/Bridge/Symfony"
        target: "https://${GH_TOKEN}@github.com/sigwinhq/xezilaires-symfony.git"
origins:
    - ^master$
