name: Build
on:
    pull_request:
    push:
        branches:
            - "master"

jobs:
    MutationTest:
        runs-on: ubuntu-latest
        env:
            PHP_VERSION: ${{ matrix.php }}
        strategy:
            matrix:
                php: [ "7.4", "8.0", "8.1" ]
                dependencies: [ lowest, highest ]
        steps:
            -
                uses: actions/checkout@v3
            -
                name: "Composer install: ${{ matrix.dependencies }}"
                run: make composer/install-${{ matrix.dependencies }}
            -
                name: Tests without mutation
                if: "matrix.php == '7.4'"
                run: make all/test/phpunit-coverage
            -
                name: Tests with mutation
                if: "matrix.php != '7.4'"
                run: make all/test
    CodeQualityAnalysis:
        runs-on: ubuntu-latest
        env:
            PHP_VERSION: ${{ matrix.php }}
        strategy:
            matrix:
                php: [ "7.4", "8.0", "8.1" ]
                dependencies: [ lowest, highest ]
        steps:
            -
                uses: "actions/checkout@v3"
            -
                name: "Composer install: ${{ matrix.dependencies }}"
                run: make composer/install-${{ matrix.dependencies }}
            -
                name: Run code quality analysis
                run: make analyze
