name: Build
on:
    pull_request:
    push:
        branches:
            - "master"

jobs:
    MutationTest:
        runs-on: ubuntu-latest
        env:
            BUILD_ENV: ${{ matrix.php }}
        strategy:
            matrix:
                php: [ "7.4", "8.0" ]
                dependencies: [ lowest, highest ]
        steps:
            -
                uses: actions/checkout@master
            -
                name: Composer install lowest dependencies
                if: "matrix.dependencies == 'lowest'"
                run: make composer-install-lowest-all
            -
                name: Composer install highest dependencies
                if: "matrix.dependencies == 'highest'"
                run: make composer-install-all
            -
                name: Tests with mutation
                run: make test-all
    CodeQualityAnalysis:
        runs-on: ubuntu-latest
        env:
            BUILD_ENV: ${{ matrix.php }}
        strategy:
            matrix:
                php: [ "7.4", "8.0" ]
                dependencies: [ lowest, highest ]
        steps:
            -
                uses: actions/checkout@master
            -
                name: Composer install lowest dependencies
                if: "matrix.dependencies == 'lowest'"
                run: make composer-install-lowest-all
            -
                name: Composer install highest dependencies
                if: "matrix.dependencies == 'highest'"
                run: make composer-install-all
            -
                name: Run code quality analysis
                run: make check-all
    DocumentationQualityAnalysis:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v1
            -
                name: Run documentation quality analysis
                run: make docs-all
